### ISSUE TITLE
zombie map # 110! error

### ISSUE THREAD

**Issue by 27rain27** [patrickgalbraith/zombicide-card-database#1]
zombie map # 110! error in the fourth line. Phew - error. Bad - right! Please fix the crashing. When will be ready the third season? Do you need help? I can write with mistakes, because I from Russia.
![110](https://cloud.githubusercontent.com/assets/11599192/6770084/42086d7a-d0c6-11e4-8a57-0265b1965f70.jpg)

**Comment by patrickgalbraith** [comment]
Closed in above commit
